# Site settings
title: J A Chowdary
email: team@jachowdary.org
description: >- # this means to ignore newlines until "baseurl:"
  Official site of J A Chowdary. His vision, work, initiatives, updates, news and all.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jachowdary
name: J A Chowdary

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
    sass_dir: ./_scss
